name: Build

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  attestations: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      wranglerVersion: "3.72.0"

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install

    - name: Build Worker
      uses: cloudflare/wrangler-action@v3
      with:
        wranglerVersion: ${{ env.wranglerVersion }}
        command: deploy --dry-run

    - name: Attest Build Provenance
      uses: actions/attest-build-provenance@v1
      with:
        subject-path: "index.js"

    - uses: actions/upload-artifact@v4
      with:
        path: index.js
